version: '3.5'

services:
  zookeeper:
    image: quay.io/strimzi/kafka:0.23.0-kafka-2.8.0
    command: [
        "sh", "-c",
        "bin/zookeeper-server-start.sh config/zookeeper.properties"
    ]
    ports:
      - "2181:2181"
    environment:
      LOG_DIR: /tmp/logs
    networks:
      - kafka-network

  kafka:
    image: quay.io/strimzi/kafka:0.23.0-kafka-2.8.0
    command: [
        "sh", "-c",
        "bin/kafka-server-start.sh config/server.properties --override listeners=$${KAFKA_LISTENERS} --override advertised.listeners=$${KAFKA_ADVERTISED_LISTENERS} --override zookeeper.connect=$${KAFKA_ZOOKEEPER_CONNECT}"
    ]
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      LOG_DIR: "/tmp/logs"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - kafka-network

  schema-registry:
    image: apicurio/apicurio-registry-mem:2.1.5.Final
    ports:
      - "8082:8080"
    depends_on:
      - kafka
    environment:
      QUARKUS_PROFILE: prod
    networks:
      - kafka-network

  producer:
    image: quarkus/worker-kafka-producer-${QUARKUS_MODE:-jvm}:1.1.0
    #image: rodrigodonizettio/quarkus-worker-kafka-producer:1.1.0
    build:
      context: worker-kafka-producer
      dockerfile: src/main/docker/Dockerfile.${QUARKUS_MODE:-jvm}
    depends_on:
      - schema-registry
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    ports:
      - "8080:8080"
    networks:
      - kafka-network

  consumer:
    image: quarkus/worker-kafka-consumer-${QUARKUS_MODE:-jvm}:1.1.0
    #image: rodrigodonizettio/quarkus-worker-kafka-consumer:1.1.0
    build:
      context: worker-kafka-consumer
      dockerfile: src/main/docker/Dockerfile.${QUARKUS_MODE:-jvm}
    depends_on:
      - schema-registry
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    ports:
      - "8081:8081"
    networks:
      - kafka-network

networks:
  kafka-network:
    name: kafkanetwork